name: Blahagraphy Personal Blog
favicon: null
layout_spectrum: 0.49718908756040037
typography_spectrum: 0.3062493542674929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7142419633455575
  lightness: 0.7124216353986412
  saturation: 0.08586319535970688
  rhythmicContrast: 0.2735570992808789
purpose: []
