name: Blahagraphy Personal Blog
favicon: null
layout_spectrum: 0.50261
typography_spectrum: 0.32976
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfb'
    - '#2a2623'
    - '#514c46'
    - '#b8b3ad'
    - '#8d867e'
  brandStrength: 0.7142419633455575
  lightness: 0.7124216353986412
  saturation: 0.5
  rhythmicContrast: 0.2735570992808789
purpose: []
